// sw-hashes.mjs — writes the fingerprint of every precached file into sw.js, and bumps
// CACHE_NAME whenever one of them changed.
//
//   node scripts/sw-hashes.mjs          write them (run after changing any cached file)
//   node scripts/sw-hashes.mjs --check  exit 1 if sw.js is out of date, change nothing
//
// ⚠️⚠️ WHY IT EXISTS (speed audit, 23 Sep 2026). sw.js used to serve a cached file AND
// fetch it again behind every request (stale-while-revalidate): dozens of requests on
// every page, and after a deploy the old worker wrote NEW files into the OLD cache, so a
// page could run half one release and half the next. It also quietly repaired a deploy
// that forgot to bump CACHE_NAME — the one thing it was good for. Now a precached file is
// served from the cache alone, and this fingerprint list replaces that repair with a
// guarantee: tests/sw-asset-hashes.test.mjs fails the moment a cached file changes and
// sw.js does not, so a forgotten bump can no longer reach main at all.
//
// ⚠️ THE FINGERPRINT IS GIT'S OWN BLOB HASH, and that is the point. It is computed from
// exactly the bytes GitHub Pages serves (checked 23 Sep 2026: all 250 precached files
// are served byte-for-byte as their blob), whatever line endings this machine's checkout
// has — `git hash-object` applies the same conversion `git add` does. The phone recomputes
// it on every file it downloads and refuses one that does not match, so a stale copy
// served for a minute after a deploy can never be stored under the new name.
//
// And because each cached file carries its fingerprint, an update copies every file whose
// fingerprint has not changed out of the previous cache instead of downloading it again.

import { readFileSync, writeFileSync, renameSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import vm from 'node:vm';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SW_PATH = `${ROOT}sw.js`;
export const HASH_LENGTH = 16;
const START = '// <asset-hashes>';
const END = '// </asset-hashes>';

// sw.js evaluated in a bare worker-shaped sandbox, so its constants can be READ — never
// parsed out of its text, which has comments in the middle of the lists.
function runWorker(swSource) {
  const ctx = {
    self: { addEventListener() {}, location: { origin: 'https://x.test', href: 'https://x.test/' } },
    caches: {}, URL, console, crypto: globalThis.crypto, TextEncoder, Response: globalThis.Response,
  };
  vm.createContext(ctx);
  vm.runInContext(swSource, ctx);
  return ctx;
}

export function readAssets(swSource) {
  return [...vm.runInContext('ASSETS', runWorker(swSource))];
}

export const fileFor = asset => (asset === './' ? 'index.html' : asset.replace(/^\.\//, ''));

// asset → the first HASH_LENGTH characters of its git blob hash, as GitHub will serve it.
export function computeHashes(assets, cwd = ROOT) {
  const files = assets.map(fileFor);
  const out = execFileSync('git', ['hash-object', '--stdin-paths'], {
    cwd, input: files.join('\n') + '\n', encoding: 'utf8',
  }).trim().split(/\r?\n/);
  if (out.length !== assets.length) throw new Error(`git hashed ${out.length} of ${assets.length} files`);
  return Object.fromEntries(assets.map((a, i) => [a, out[i].slice(0, HASH_LENGTH)]));
}

export function hashBlock(hashes) {
  const lines = Object.entries(hashes).map(([a, h]) => `  ${JSON.stringify(a)}: '${h}',`);
  return [
    START,
    '// GENERATED by scripts/sw-hashes.mjs — never edit by hand. Each precached file\'s git blob',
    '// hash (first 16 characters): the phone checks every download against it, and an update',
    '// copies a file whose hash has not changed out of the previous cache instead of fetching it.',
    'const ASSET_HASHES = {',
    ...lines,
    '};',
    END,
  ].join('\n');
}

// The fingerprints sw.js carries now, or null before it has any.
export function currentHashes(swSource) {
  const ctx = runWorker(swSource);
  try { return { ...vm.runInContext('ASSET_HASHES', ctx) }; } catch { return null; }
}

function main() {
  const check = process.argv.includes('--check');
  let sw = readFileSync(SW_PATH, 'utf8').replace(/\r\n/g, '\n');
  const assets = readAssets(sw);
  const hashes = computeHashes(assets);
  const before = currentHashes(sw);
  const changed = assets.filter(a => !before || before[a] !== hashes[a]);
  const extra = before ? Object.keys(before).filter(a => !assets.includes(a)) : [];

  if (!changed.length && !extra.length) {
    console.log(`sw.js is up to date: ${assets.length} fingerprints match.`);
    return;
  }
  if (check) {
    console.error(`sw.js is OUT OF DATE: ${changed.length} changed, ${extra.length} no longer cached. Run: node scripts/sw-hashes.mjs`);
    process.exit(1);
  }

  const block = hashBlock(hashes);
  if (sw.includes(START)) {
    sw = sw.slice(0, sw.indexOf(START)) + block + sw.slice(sw.indexOf(END) + END.length);
  } else {
    const marker = '\n];\n';
    const at = sw.indexOf(marker, sw.indexOf('const ASSETS = ['));
    if (at === -1) throw new Error('could not find the end of ASSETS in sw.js');
    sw = sw.slice(0, at + marker.length) + '\n' + block + '\n' + sw.slice(at + marker.length);
  }

  // A cached file changed: the phones must be told, which is what a new CACHE_NAME does.
  let version = null;
  sw = sw.replace(/const CACHE_NAME = 'theitalianclub-v(\d+)';/, (_, n) => {
    version = Number(n) + 1;
    return `const CACHE_NAME = 'theitalianclub-v${version}';`;
  });
  if (version === null) throw new Error('could not find CACHE_NAME in sw.js');
  // The prose states the precache size; tests/precache-install.test.mjs holds it to ASSETS.
  sw = sw.replace(/(\d+)-file precache/g, `${assets.length}-file precache`)
         .replace(/all (\d+) files/g, `all ${assets.length} files`);

  // Written beside and renamed over, never truncated in place.
  writeFileSync(`${SW_PATH}.tmp`, sw);
  renameSync(`${SW_PATH}.tmp`, SW_PATH);
  console.log(`sw.js: ${changed.length} fingerprint(s) changed${extra.length ? `, ${extra.length} removed` : ''} → CACHE_NAME v${version}.`);
  changed.slice(0, 20).forEach(a => console.log(`  ${a}`));
  if (changed.length > 20) console.log(`  … and ${changed.length - 20} more`);
}

const invoked = process.argv[1]
  && resolve(process.argv[1]).toLowerCase() === fileURLToPath(import.meta.url).toLowerCase();
if (invoked) main();
